project:
  type: website
  resources:
    - "images/twitter-card.png"
    - "materials"
  render:
    - "*.qmd"
    - "!materials"
    - "!README.Rmd"
  pre-render: zip.R

website:
  page-navigation: true
  title: "Tidy time series & forecasting in R"
  description: "Homepage for NYR 2023 time series workshop"
  site-url: "https://workshop.mitchelloharawild.com/nyr2023"
  
  repo-url: https://github.com/mitchelloharawild/nyr2023
  repo-actions: [edit, issue]

  # opengraph: true
  twitter-card:
    creator: "@mitchoharawild"
    image: "/images/twitter-card.png"

  favicon: "/images/fable.svg"

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    right: "&copy; Copyright 2022, Mitchell O'Hara-Wild"
    background: "#426D98"

  navbar:
    background: "#426D98"
    pinned: true
    align: center
    right:
      - icon: download
        text: Downloads
        menu: 
          - text: Everything
            href: 'https://github.com/mitchelloharawild/workshop-nyr2023/archive/refs/heads/main.zip'
          - text: Slides
            href: 'slides.zip'
          # - text: Lab sessions
          #   href: 'labs.zip'
      - icon: file-certificate
        href: license.qmd
      - icon: github
        href: https://github.com/mitchelloharawild/nyr2023
    left:
      - text: Sessions
        menu: 
          - text: Background
            href: sessions/day1/00_intro.qmd
          - text: Introduction to tsibbles
            href: sessions/day1/01_tsibble.qmd
          - text: Time series graphics
            href: sessions/day1/02_graphics.qmd
          - text: Transformations
            href: sessions/day1/03_transformations.qmd
          - text: Seasonality and trends
            href: sessions/day1/04_decomposition.qmd
          - text: Time series features
            href: sessions/day1/05_features.qmd
          - text: Introduction to forecasting
            href: sessions/day2/06_forecasting.qmd
          - text: Exponential smoothing
            href: sessions/day2/07_ets.qmd
          - text: ARIMA models
            href: sessions/day2/08_arima.qmd
          - text: Dynamic regression
            href: sessions/day2/09_dynreg.qmd
          - text: Hierarchical forecasting
            href: sessions/day2/10_hierarchical.qmd
      - href: schedule.qmd

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Open Sans"
    include-after-body: plausible.html
